cilium/image-tools

- images/iproute2/build-iproute2-cross-aarch64.sh
- images/iproute2/build-iproute2-native.sh
This PR adds the 'ss' tool from the iproute2.
Related: #11667
Signed-off-by: Swaminathan Vasudevan <svasudevan@suse.com>
> Add 'ss' tool from the iproute2

- images/llvm/checkout-llvm.sh
We have this in our generated BPF code quite a lot, so cherry-pick the
work that John recently upstreamed into LLVM:
- https://github.com/llvm/llvm-project/commit/29bc5dd19407c4d7cad1c059dea26ee216ddc7ca
- https://github.com/llvm/llvm-project/commit/13f6c81c5d9a7a34a684363bcaad8eb7c65356fd
> cilium, llvm: cherry pick MOV_32_64 BPF code-gen optimization

- .github/workflows/images.yaml
- .github/workflows/pr-checks.yaml
- scripts/build-image.sh
- scripts/get-image-digest.sh
- scripts/lint.sh
> Update maker image 

- scripts/build-image.sh
This broke when debug clause was added.
> Fix issue with false-positive return code

- README.md
- images/compilers/Dockerfile
- images/compilers/install-bazel.sh
- images/compilers/install-deps.sh
> Include bazel in compilers image

- images/bpftool/Dockerfile
- images/compilers/install-deps.sh
- images/iproute2/Dockerfile
Avoid apt-get configuration questions being prompted.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> Set DEBIAN_FRONTEND=noninteractive

- .github/workflows/images.yaml
> Push all images to quay.io

- images/compilers/Dockerfile
- images/llvm/Dockerfile
> Add missing empty files to compiles and llvm images

- images/bpftool/test/spec.yaml
> Update bpftool version string test

- README.md
Fix some typos and spelling mistakes found in the README.
> Fix typos in REAMDE.md

- images/maker/go.mod
Fixes https://github.com/cilium/image-tools/runs/1326284731?check_suite_focus=true
> Fix dependency build issue

- .github/workflows/images.yaml
- .github/workflows/kube-test.yaml
- .github/workflows/pr-checks.yaml
- Makefile
- images/ca-certificates/Dockerfile
- images/maker/Dockerfile
- images/startup-script/Dockerfile
- scripts/build-image.sh
- scripts/get-image-digest.sh
- scripts/lint.sh
> Use new maker image

- .github/workflows/kube-test.validate-kind-cluster.sh
- .github/workflows/kube-test.yaml
- images/kube-test/configure.sh
- 2-node (untaited master)
- Docker for Desktop
> Add a variety of canned kind configs

- scripts/find-commit-for-tree-hash.sh
Signed-off-by: Ilya Dmitrichenko <errordeveloper@gmail.com>
> Add a script to lookup commit hash from a tree hash

- .github/workflows/images.yaml
> .github: update github secrets

- .github/workflows/images.yaml
> .github: set right secret

- .github/workflows/images.yaml
- .github/workflows/kube-test.yaml
- .github/workflows/pr-checks.yaml
- images/bpftool/Dockerfile
- images/compilers/Dockerfile
- images/iproute2/Dockerfile
- images/llvm/Dockerfile
- images/startup-script/manage-startup-script.sh
- scripts/build-image.sh
- scripts/get-image-digest.sh
- scripts/lint.sh
Avoid hitting Dockerhub rate limiting.
> Switch Cilium images to quay.io

- images/bpftool/checkout-linux.sh
Needed for bpftool's feature probing on more recent kernels.
> Update bpftool to more recent bpf-next revision

- Makefile
- images/bpftool/Dockerfile
- images/compilers/Dockerfile
- images/iproute2/Dockerfile
- images/llvm/Dockerfile
- scripts/update-ubuntu-image.sh
Also add a script to automate updates. See first commit for details.
> Update base Ubuntu 20.04 image to latest version

- images/maker/Dockerfile
With yq and jq.
Signed-off-by: Nate Sweet <nathanjsweet@pm.me>
> Update Image Maker

- .github/workflows/images.yaml
- .github/workflows/pr-checks.yaml
- scripts/build-image.sh
- scripts/get-image-digest.sh
- scripts/lint.sh
Signed-off-by: Nate Sweet <nathanjsweet@pm.me>
> Update Scripts with New Image Maker

- Makefile
Ran makefile locally to build the iperf image
Signed-off-by: Joe Talerico <rook@isovalent.com>
> Fixing path for iperf

- images/checkpatch/README.md
- images/checkpatch/fixes/ignore-_Static_assert.diff
Add an exception for _Static_assert in the CamelCase tests.
> allow C's _Static_assert

- .github/workflows/images.yaml
- .github/workflows/pr-checks.yaml
ubuntu-18.04 is deprecated, see
https://github.com/actions/virtual-environments/issues/6002
> ci: update to ubuntu-22.04 environment

- Makefile
Build arm64 images also for maker-image, compilers-image, and test-verifier-image.
> build: Multiarch maker-image, compilers-image, and test-verifier-image

- Makefile
- scripts/build-image.sh
I experimented with doing a build of Cilium fully from scratch while quay was down today. I have two suggestions for making this process a bit easier in the future. Please see commits for details.
From my understanding, these changes shouldn't impact any GHA workflows.
Thanks!
> Fixes for Manual Builds
