cilium/image-tools

- Dockerfile.bpftool
For CONFIG_HZ and getpeername hook.
> cilium, bpftool: pull in latest changes from bpf-next

- images/bpftool/checkout-linux.sh
Commit 61d38f67f109 ("Build images in GitHub Actions (#3)") pointed
bpftool back to an old revision which breaks the expectations from
cilium-runtime. Move it forward in time to something recent.
> docker, bpftool: fix checking out too old bpftool revision

- .github/workflows/images.yaml
- Makefile
- images/maker/build-credentials-helper.sh
- scripts/build-image.sh
- handle any number of registies
- force re-build when image is missing in either of the registries
- bump docker-credential-env to ensure quay.io URLs are handled well
- enable buildkitd debug logs
- improve registry check reliability
/xref https://github.com/cilium/image-tools/issues/11
> Add support for publishing images to multiple registries

- images/llvm/build-llvm-cross-aarch64.sh
BPF bytecode is the target, it is independent of CPU architecture.
The configuration was originally overlooked in #3.
> llvm: Fix configuration of the AArch64 build

- .github/workflows/images.yaml
- Makefile
- images/ca-certificates/.dockerignore
- images/ca-certificates/Dockerfile
This image is intended for use as `FROM scratch` equivalent, except
it has common CA certs.
> ca-certificates: New image

- scripts/build-image.sh
- scripts/update-alpine-base-image.sh
- scripts/update-compilers-image.sh
- scripts/update-maker-image.sh
This failed here https://github.com/cilium/image-tools/runs/772247032?check_suite_focus=true.
We should have a way of testing some of this logic before merging, I opened https://github.com/cilium/image-tools/issues/38.
> scripts: Fix a bug in script path, use `${script_dir}` consistently

- scripts/build-image.sh
- scripts/update-alpine-base-image.sh
- scripts/update-compilers-image.sh
- scripts/update-maker-image.sh
Works in this repo, but doesn't work when copied under a different path in Cilium repo.
> scripts: Determine `script_dir` prior to firs `cd`

- Makefile
- images/compilers/Dockerfile
- images/compilers/test/spec.yaml
- images/maker/Dockerfile
- images/tester/Dockerfile
- images/tester/cst/main.go
- images/tester/test/spec.yaml
- scripts/build-image.sh
- scripts/update-golang-image.sh
- scripts/update-tester-image.sh
Another follow-up from #43 (ref #5).
> Compilers image tests

- .hadolint.yaml
- Makefile
- images/bpftool/Dockerfile
- images/bpftool/checkout-linux.sh
- images/bpftool/test/spec.yaml
- images/compilers/Dockerfile
- images/iproute2/Dockerfile
- images/iproute2/test/spec.yaml
- images/llvm/Dockerfile
- images/llvm/build-llvm-cross-aarch64.sh
- images/llvm/build-llvm-native.sh
- images/llvm/test/spec.yaml
- images/llvm/test/test.c
- use latest tester image
- update bpftool since commit used previously
is now missing from bpf-next tree
- ensure final images have system dependencies
- copy test spec into final image, so downstream
builds can run the test to verify resulting
images pass the tests
- move output files under `/usr/local/bin`
Fixes: #5
> Add test to bpftool, iproute2 & llvm images

- images/bpftool/Dockerfile
- images/iproute2/Dockerfile
- images/llvm/Dockerfile
This is just to keep things up-to-date, the image was update due to tests being added. So this just ensure new tested image will be used.
> Use new compilers image

- .github/workflows/images.yaml
- .github/workflows/kube-test.validate-kind-cluster.sh
- .github/workflows/kube-test.yaml
- .gitignore
- Makefile
- README.md
- images/kube-test/.dockerignore
- images/kube-test/Dockerfile
- images/kube-test/configure.sh
- scripts/build-image.sh
This is image is similar to maker image, but for now it's preferred to not bloat maker image, but there may be good reasons for consolidation in the future.
The motivation to have a kind image of our own is to make CI implementation more portable, i.e. avoid using community GitHub actions. One benefit is that developers can run exactly the same container images locally, but another is that in the future CI can be moved to another platform as it has moved in the past. This PR updates documentation to include a section covering portability in more detail.
> Add tester image that includes kubectl, helm, docker and kind

- scripts/build-image.sh
There is no need to check for local presence, as if it was built on
the same host recently, the build cache will be used and it should
be very quick.
The build was forced in PR mode and otherwise on a local branch,
due to `-dev` suffix, but it broke on master.
See https://github.com/cilium/image-tools/actions/runs/151376302
> Ensure images are always re-built in local mode

- images/maker/Dockerfile
- images/tester/Dockerfile
- scripts/update-golang-image.sh
Use 1.15.0 explicitly instead og 1.15 to avoid automatic updates
whenever a new 1.15.x point release is made, also see
https://github.com/cilium/cilium/pull/12853#discussion_r469182516
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> Bump Go images to 1.15

- images/compilers/install-bazel.sh
- images/compilers/test/spec.yaml
Envoy and envoy-build-tools already support and require newer versions
of Bazel.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
> compilers: Add Bazel 3.3.1 and 3.4.1 versions

- images/bpftool/checkout-linux.sh
We need this in order to run 'bpftool feature probe macro' with the
new UAPI definitions from bpf.h helper UAPI.
> bpftool: update bpftool image to newer sha

- images/bpftool/checkout-linux.sh
We need this in order to run 'bpftool feature probe macro' with
the new UAPI definitions from bpf.h helper UAPI (redirect_peer()
in particular).
> bpftool: update bpftool image to newer sha again

- images/bpftool/test/spec.yaml
Same as done in a35f2e9d36a1 ("Update bpftool version string test") where
it slipped through given tests are only run after merge and not on PRs. :-/
> bpftool: fix up test for versioning

- images/checkpatch/Dockerfile
- images/checkpatch/README.md
- Remove the `WORKDIR` directive (and simply uses absolute paths where necessary instead). This is to avoid any confusion when using the container with a GitHub action, for which the working directory is set through the `GITHUB_WORKSPACE` variable. It should not matter much as we need to mount a volume to point to Cilium's source code to check in any case, but better be safe than sorry.
- Remove the `/opt` prefix for the checkpatch directory in the container, as installing under the root seems a common practice and the prefix only makes path names longer to type.
- Add an entrypoint to the container image, as this should be constant for all invocations of the container.
- Update the documentation for the checkpatch image accordingly, improve example command line (and fix a typo).
> checkpatch: improve Dockerfile

- images/checkpatch/Dockerfile
Curl is necessary to run the `checkpatch.sh` script as a GitHub Action, but it is not present on the Alpine image by default. Let's install it when building the image.
> checkpatch: add curl to the image

- images/llvm/build-llvm-cross-aarch64.sh
- images/llvm/build-llvm-native.sh
The `llvm-objcopy` binary will be used in the 4.19 CI test for verifier errors. It is required to remove global data sections which libbpf rejects in newer kernels.
The new cilium-llvm image will then be used in https://github.com/cilium/cilium/pull/13953, which I'll need to update.
> llvm: Include llvm-objcopy in the image

- images/iproute2/checkout-iproute2.sh
This version includes a fix for loading BPF programs compiled with debug
symbols on kernels which do not support BTF.
> iproute2: bump to latest revision of static-data branch

- images/checkpatch/README.md
- images/checkpatch/fixes/recognize-co-authored-by.diff
GitHub supports the annotation Co-authored-by for commits with several authors. Checkpatch should recognize it as well to avoid false positives.
> checkpatch: Support GitHub's Co-authored-by

- images/compilers/install-bazel.sh
There's no need to keep older versions of bazel as we are only using
3.7.x, so we can remove the older ones.
> compilers: update bazel to 3.7.2 and remove older versions

- images/compilers/test/spec.yaml
Fixes: e4680365fb11 ("compilers: update bazel to 3.7.2 and remove older versions")
> update compilers test

- Makefile
As it is not possible to fine tune repository permissions to a
particular DockerHub account, we can't reuse it in multiple
repositories. We will use quay.io for the images build in this
repository.
> Makefile: remove ability to push to docker.io

- images/checkpatch/Dockerfile
The jq version 1.5 provided on Alpine 3.11 has a vulnerability [0], as reported by the quay.io scanner [1].
Let's update to a newer image, which contains jq v1.6-rc1 [2]. This image does not have "patch" installed, so we need to pull the package _before_ patching checkpatch.pl.
[0] https://cve.circl.lu/cve/CVE-2016-4074
[1] https://quay.io/repository/cilium/cilium-checkpatch/manifest/sha256:fedf16fe5d8d1b8d2d6f62371725812e301796e0c5c5379c85d9af159e16c8b7?tab=vulnerabilities
[2] https://pkgs.alpinelinux.org/packages?name=jq&branch=v3.13
> checkpatch: update base image for Alpine

- images/checkpatch/checkpatch.sh
When retrieving the list of commits for the PR, use the `$GITHUB_REPOSITORY` variable set by the GitHub action instead of hardcoding the name of the repository. This is cleaner, and would potentially be easier to reuse for other repositories.
> checkpatch: use $GITHUB_REPOSITORY to pass the repo

- .github/workflows/images.yaml
This will make all images to be published in quay.io
> .github: force rebuild of all images

- .github/workflows/images.yaml
This reverts commit b7c81b77b2624bf541e0e5474488f7c0d677297a.
> Revert ".github: force rebuild of all images"

- images/maker/build-go-deps.sh
As of Go 1.16 the setting for `GO111MODULE` defaults to `on` which leads
to the `go build` commands in images/maker/build-go-deps.sh no longer
working. As a temporary measure set `GO111MODULE=off` for these commands
but add a TODO comment that they should use versioned `go install` commands
instead.
Follow-up fix for #113
> images/maker: set GO111MODULE=off for go build commands

- images/maker/build-go-deps.sh
Instead of using `go install <pkg>@<version>`, add `go mod download`,
as `go.mod` file is already present with the versions. Older version
of Go used to implicitly perform the download, but looks like it refuses
to do it now without a `go.sum`.
This is a follow-up to #115
> images/maker: fix building Go deps

- .github/workflows/images.yaml
- CODEOWNERS
- Makefile
- README.md
- images/test-verifier/Dockerfile
- images/test-verifier/README.md
- images/test-verifier/install-tc-ip.sh
- images/test-verifier/iproute2.diff
This new image will be used in the K8sVerifier test in replacement for cilium-builder. It includes a custom patch of iproute2 to work around issues with the log buffer size.
> test-verifier: New image for use in K8sVerifier test

- .github/workflows/kube-test.yaml
- .github/workflows/pr-checks.yaml
Otherwise, when opening PRs from branches on
github.com/cilium/image-tools, each workflow gets instantiated twice,
once for the `on: pull_request` and once for `on: push`. Avoid this by
restricting `on: push` to pushes to the master branch.
FWIW, this is done in the same way on the github.com/cilium/cilium repo.
> .github: only run workflows for pushes to master branch

- images/maker/build-go-deps.sh
There appears to be a subtle difference between `go mod download`
and `go mod download all`. This change fixes the following error:
```
#25 0.469 + mkdir -p /out/usr/local/bin
#25 0.471 + go mod download
#25 86.44 + go build -ldflags '-s -w' -o /out/usr/local/bin/docker-credential-env github.com/errordeveloper/docker-credential-env
#25 86.50 missing go.sum entry for module providing package github.com/errordeveloper/docker-credential-env; to add:
#25 86.50 	go mod download github.com/errordeveloper/docker-credential-env
```
> images/maker: fix building Go deps (again)

- images/checkpatch/checkpatch.sh
This set contains a few fixes for parsing commit objects when checkpatch runs in a GitHub action, and for detecting missing descriptions in commits. Please refer to individual commit logs for details.
Context: We want to detect commits such as [this one](https://github.com/cilium/cilium/pull/16896/commits/f9845d257cb3e3ff66ab6f9608935345c631db67), where the blank line between the object and the description was omitted, and resulted in a very long commit object for git (although GitHub seems to handle it better).
> checkpatch: fix issues with commit object/description checks

- images/checkpatch/checkpatch.sh
These are two short commits for the checkpatch image.
The first one is a simple fix for the `::warning::` prefix, so that warnings are displayed (and reported) better on the GitHub interface.
The second one is more important, and fix an issue that results in the check being marked as successful on GitHub even when issues are reported.
> checkpatch: fix bash script (warning prefix and exit status for GH action)

- images/iproute2/checkout-iproute2.sh
Pull in backport from https://github.com/cilium/iproute2/pull/15 .
> Update iproute2 to pull in managed neighbor backports

- images/checkpatch/checkpatch.sh
Currently, the commit index reported as part of the commit list is off
by one, e.g. in an example from
https://github.com/cilium/cilium/pull/18247:
```
Retrieved 5 commits from PR #18247
{[0/5] option: correct godoc for (*DaemonConfig).TunnelingEnabled}
{[1/5] maps/tunnel: mark TunnelMap as NonPersistent on creation}
{[2/5] datapath, tunnel: correctly ignore ENOENT on tunnel mapping delete}
{[3/5] daemon: open or create tunnel map cache only if needed}
{[4/5] datapath/linux: don't attempt to delete old tunnel map entries on node addition}
```
See https://github.com/cilium/cilium/runs/4505300593?check_suite_focus=true
Fix this by passing the 1-based index, not the 0-based index to function
`check_commit`.
> images/checkpatch: fix index off-by-one in commit list

- images/bpftool/Dockerfile
- images/ca-certificates/Dockerfile
- images/checkpatch/Dockerfile
- images/compilers/Dockerfile
- images/iproute2/Dockerfile
- images/llvm/Dockerfile
- images/maker/Dockerfile
- images/startup-script/Dockerfile
- images/tester/Dockerfile
- scripts/update-alpine-base-image.sh
Quay security scanner reports several vulnerabilities in the alpine 3.11
base image we currently use for images. Update to latest alpine 3.15 to
pull in fixes for these vulnerabilities.
> images: update alpine base image to 3.15

- images/compilers/install-deps.sh
Otherwise installation of up-to-date packages and thus the image build
fails.
> images/compilers: add focal-updates to apt sources

- images/maker/go.mod
This fixes the build of the go tools for the maker image.
Fixes: 6d772bf597ca ("images/maker: add +tools import for dependencies")
> images/maker: revert go.mod update to go 1.17

- images/tester/cst/main.go
The bool arg to test.ProcessResults was changed upstream in
https://github.com/GoogleContainerTools/container-structure-test/pull/254
Fixes: 5cfd469de1b1 ("images/tester: update container-structure-test to latest version")
> images/tester: fix build after container-structure-test update

- images/iproute2/checkout-iproute2.sh
This is needed to pick up a fix that sets the proper log level in libbpf, if a verbose flag is passed to tc and fix https://github.com/cilium/cilium/issues/18281.
Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>
> iproute2: update to latest libbpf-static-data

- images/bpftool/checkout-linux.sh
This is needed to pick up new miscellaneous feature probes, for bounded loops and instruction set extensions.
> bpftool: Update to latest bpf-next

- images/bpftool/test/spec.yaml
CI test fails with:
> Error: Expected string 'bpftool\ v5\.15\.0-rc3' not found in output 'bpftool v5.16.0-rc7
Fix this by updating the bpftool version.
Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>
> bpftool/test: update bpftool version

- .github/workflows/images.yaml
- .github/workflows/pr-checks.yaml
- images/bpftool/Dockerfile
- images/compilers/Dockerfile
- images/compilers/install-deps.sh
- images/compilers/test/spec.yaml
- images/iproute2/Dockerfile
- images/llvm/Dockerfile
- scripts/build-image.sh
- scripts/get-image-digest.sh
- scripts/lint.sh
- scripts/update-ubuntu-image.sh
This commit is to bump all images to the latest ubuntu LTS 22.04.
Signed-off-by: Tam Mach <tam.mach@cilium.io>
Testing was done locally with make all-images, to make sure there is no failure, as well as dirty changes.
> image: Bump the images to ubuntu LTS 22.04

- images/bpftool/Dockerfile
- images/compilers/Dockerfile
- images/compilers/install-deps.sh
- images/compilers/test/spec.yaml
- images/iproute2/Dockerfile
- images/llvm/Dockerfile
- scripts/update-ubuntu-image.sh
This reverts commit a3c6a88e64eabde7a1acaf67992f229db1a0e053.
The new images based on Ubuntu 22.04 are failing Cilium's CI, so let's revert back temporarily so that not all dependency updates are blocked.
> Revert "image: Bump all images to ubuntu LTS 22.04"

- images/iproute2/checkout-iproute2.sh
- images/iproute2/checkout-libbpf.sh
Context: https://github.com/cilium/cilium/issues/20288#issuecomment-1185551102
To work around the -EPERM returned when trying to load programs in the CI tests, we want tc to raise the memlock rlimit for us. Let's get the updates from:
- https://github.com/cilium/libbpf/pull/2
- https://github.com/cilium/iproute2/pull/18
> iproute2: Bump iproute2/libbpf to get rlimit bump

- .github/workflows/images.yaml
- .github/workflows/pr-checks.yaml
- images/bpftool/Dockerfile
- images/compilers/Dockerfile
- images/compilers/install-deps.sh
- images/compilers/test/spec.yaml
- images/iproute2/Dockerfile
- images/llvm/Dockerfile
- scripts/build-image.sh
- scripts/get-image-digest.sh
- scripts/lint.sh
- scripts/update-ubuntu-image.sh
This commit is to bump all images to the latest ubuntu LTS 22.04.
Signed-off-by: Tam Mach <tam.mach@cilium.io>
Testing was done with temp commit, which was removed after.
https://github.com/cilium/image-tools/runs/7857674066?check_suite_focus=true
> image: Bump all images to ubuntu LTS 22.04

- Makefile
- images/network-perf/Dockerfile
The image used in `cilium connectivity test --perf` is `quay.io/cilium/network-perf` which is
only compiled for `linux/amd64` and is not available for `linux/arm64`.
Here we propose:
* bump the base image used for `network-perf` to `ubi8:8.6`
* bump the `iperf` tool to 3.12
* fetch the `netperf` from this tag https://github.com/HewlettPackard/netperf/commit/80bf19d563eebd1eca23f4092f96819296020fa5 to allow for arm64 builds
* have a slightly better handling of the archive and folder names to allow easier version bumps when needed
* enable `linux/arm64` builds for `network-perf`
> Enable network-perf for linux/arm64

- .github/workflows/images.yaml
- Makefile
- images/iptables/Dockerfile
This image is used to build iptables deb packages from source (currently version 1.8.8-1), which will then be imported in the cilium-runtime image.
> Add iptables builder image

- .github/workflows/images.yaml
- Makefile
- images/iptables-20.04/Dockerfile
- images/iptables/Dockerfile
This change adds a new iptables-20.04 that builds the selected iptables version (1.8.8 in this case) for Ubuntu 20.04.
Additionally, instead of building from whatever is currently Debian testing, it uses the Debian snapshot infrastructure, to build a specific version, so that the Dockerfile won't break in the future.
If we want to change the version to a different one, we can do that by picking a future date.
I have tested that these two images build successfully and the output can be used to install iptables in the v1.13 and v1.12 branches respectively.
> Build iptables using snapshots, for Ubuntu 20.04 and 22.04

- images/iptables-20.04/Dockerfile
The snapshots are signed with both keys, so using buster's is enough. Also remove unneeded apt-get update in between.
> Use buster's key instead of bullseye

- images/llvm/checkout-llvm.sh
Cherry-pick the upstream LLVM commit ea72b0319d7b ("BPF: make 32bit register spill with 64bit alignment"). Since the upstream kernel commit 354e8f1970f8 ("bpf: Support <8-byte scalar spill and refill"), the kernel assumes that 32-bit spilled registers have 64-bit alignment on the stack, otherwise the verifier can't preserve the boundaries and can generate false positives.
Although this patch alone is not enough to fix the root cause of the issue that appeared in Cilium before Cilium commit efb5d6509fea ("bpf: Fix verifier issue in fib_redirect") worked around it, it's the first step that may also help in some other cases.
> llvm: Cherry-pick the 64-bit stack alignment patch

- Makefile
`checkpatch` should run on/have a multiarch image for arm64 linux boxes (like mine).
> Nit: multiarch `checkpatch`

- images/ca-certificates/Dockerfile
- images/checkpatch/Dockerfile
- images/maker/Dockerfile
- images/startup-script/Dockerfile
- images/tester/Dockerfile
- scripts/update-alpine-base-image.sh
Update Alpine by bumping up the version in update-alpine-base-image.sh and running `make update-alpine-base-image`.
Ref: https://hub.docker.com/_/alpine/tags
> Pick up Alpine 3.18.0

- images/llvm/checkout-llvm.sh
As indicated in the kernel patch set - https://lore.kernel.org/bpf/20210325015234.1548923-1-kafai@fb.com/.
> llvm: Cherry pick commit for kfunc support

- images/llvm/checkout-llvm.sh
Alas, we are finally hitting merge conflicts.
```
CONFLICT (content): Merge conflict in llvm/lib/Target/BPF/BTFDebug.cpp
warning: inexact rename detection was skipped due to too many files. 
warning: you may want to set your merge.renamelimit variable to at least 20590 and retry the command.
error: could not apply 886f9ff53155... BPF: add extern func to data sections if specified
```
I've started an internal thread to discuss the conflicts.
> Revert "Cherry pick commit for kfunc support"

- images/checkpatch/checkpatch.sh
Grouping logs by commit in the output of the GitHub workflow provides a nicer interface than just displaying separators, but it turns out to be more cumbersome in case of errors, because users have no way to know what group contains the error and they have to manually expand all groups, which has proved annoying. There doesn't seem to be an option to auto-expand the groups, so let's remove them altogether.
> checkpatch: Remove grouping logs in GHA output

- Makefile
Otherwise the build will fail if PLATFORMS is not defined on make invocation.
Fixes: 0ee97a0754ad ("Allow users to overwrite build platforms")
> Makefile: fix definition of PLATFORMS variable

- .github/workflows/images.yaml
Due to a typo ("output" instead of "outputs") images weren't pushed after build even if $PUSH was set to true.
Fixes: 8d54797a18b8 ("ci: build images on pull requests")
> ci: fix pushing of images on build if PUSH=true

- images/bpftool/checkout-linux.sh
- images/bpftool/test/spec.yaml
We want our bpftool image to support dumping netkit programs, with kernel commit torvalds/linux@bec981a4add6 ("bpftool: Extend net dump with netkit progs"). Let's update to a recent version: v7.4.0 was tagged yesterday, let's use the corresponding kernel commit.
Supersedes #270 (workflow fails because I opened the PR from a fork). (Apologies Lorenz!)
> images/bpftool: Update bpftool image

- images/checkpatch/Dockerfile
The latest checkpatch images complain:
/checkpatch/checkpatch.sh: line 155: /checkpatch/checkpatch.pl: Permission denied
Let's fix the permissions for the script we download.
Fixes: e2a7f29cbf2e
> checkpatch: Fix checkpatch.pl permissions

- images/llvm/checkout-llvm.sh
- images/llvm/test/spec.yaml
Fixes for Clang 17 were merged into the Cilium codebase:
b91046955d6b ("datapath: Ignore new debug ELF prefixes")
6e18eb020b68 ("bpf: Fix compatibility with Clang 17 in __lb6_affinity_backend_id")
3740e9db8fef ("bpf: Fix "R2 !read_ok" verifier error with LLVM 17")
c6fe6b8e2546 ("bpf/tests: Fix `conntrack_test.c` in prep for Clang update")
4dd6b0a4f97f ("bpf/tests: Fix undefined behavior in memcmp MAC addresses")
f87b5dc5e0b2 ("bpf/tests: Fix undefined behavior in EXPECTED_DEST_MAC")
and the complexity measurements were performed, so now the LLVM image can be upgraded.
> llvm: Upgrade to LLVM 17.0.6

- images/startup-script/Dockerfile
- scripts/build-image.sh
This PR contains two commits, one for adjusting the way we install `ca-certificates` in the `startup-script` image, and one to enable image builds in PRs from forks. Please see individual commits for details.
I opened a draft PR in `cilium/cilium` to test the changes to this image, see https://github.com/cilium/cilium/pull/33414. The helm-based checks are failing because I didn't update the generated documentation. All other checks that actually use the new `startup-script` image are passing.
> startup-script: Adjust ca-certificates install to only copy certs

- .github/workflows/images.yaml
- Makefile
- images/bpftool/Dockerfile
- images/compilers/Dockerfile
- images/compilers/install-deps.sh
- images/iptables/Dockerfile
- images/llvm/Dockerfile
- images/llvm/checkout-llvm.sh
- images/llvm/test/spec.yaml
Testing was done in https://github.com/cilium/cilium/pull/33264
> ubuntu: Bump to latest LTS 24.04

- images/network-perf/Dockerfile
- scripts/make-image-tag.sh
This commit change the way of tagging image, from using git-lfs-tree sha256 to using directory's last commit timestamp. It will permit renovate to sort versions and update properly new images, where renovate wasn't able to do so before due to its inability to sort SHAs.
The git log command, when given a specific directory in parameter, retrieve the last commit were changes were made in said directory. This means that we can ensure different image versions same as used to be with git-tree.
Renovate can sort versions from left to right, using a timestamp as a tag value allows it to retrieve the latest version deployed with ease.
> Use latest directory commit timestamp as tag

- README.md
Following the pr #286, update of the README.md about how the tagging mechanic works
> Fix: update readme after new tagging mechanic

- .github/workflows/images.yaml
- scripts/make-image-tag.sh
actions/checkout by default retrieve only the last commit of the repository. If we want the tagging mechanic to work properly we need the full history so we can know the actual real last commit of the image directory when tagging
> fix: get git history to make tagging mechanic work properly

- .github/workflows/images.yaml
- Makefile
- images/clang-format/Dockerfile
- images/clang-format/build-llvm-cross-aarch64.sh
- images/clang-format/build-llvm-native.sh
- images/clang-format/checkout-llvm.sh
This PR part of an effort to start using clang-format in the Cilium project to format BPF code. This PR adds a minimal image for clang-format. It is a variation of the llvm image, main difference is that the resulting binaries are statically compiled. This allows them to run in a scratch image, drastically reducing the size of the docker image. It also allows for the possibility to copy the binary out of the docker image to be ran on local machines, for example to integrate into editors. Making it easy to ensure we use the same tool both locally and in CI to avoid formatting irregularities due to version mismatches.
> images: Add clang-format image

- images/maker/Dockerfile
This PR updates hadolint in the `maker` image from [1.17.6](https://github.com/hadolint/hadolint/releases/tag/v1.17.6) to [2.12.0](https://github.com/hadolint/hadolint/releases/tag/v2.12.0).
Additional changes:
* Install the right version of `hadolint` based on the arch instead of always installing the amd64 one.
* Fix [`FromAsCasing`](https://docs.docker.com/reference/build-checks/from-as-casing/) violations
* Use the multi-arch version of the crane image instead of its amd64 version, see this warning:
```
WARNING: InvalidBaseImagePlatform
Base image gcr.io/go-containerregistry/crane:latest@sha256:5583664dfe9bb06b3e09ad612c91bd8378653d3ebec2e0b5e3d3d2c046b3b0a5 was pulled with platform "linux/amd64", expected "linux/arm64" for current build
```
<details>
<summary>Details of the new …
> maker: Update hadolint to 2.12.0

- .github/workflows/images.yaml
Build all images in parallel
New take on #106 where the matrix is generated dynamically so there's no static list that needs to be manually updated when a new image is added to the repo.
> ci: Build all images in parallel

- .github/workflows/images.yaml
`make lint` already runs as part of the separate [`Run static checks`](https://github.com/cilium/image-tools/blob/master/.github/workflows/pr-checks.yaml) workflow and does a repo-wide check of all Dockerfiles.
The step that's being removed here causes `make lint` to also run for every single image build job, which is unnecessary.
> ci: Remove duplicate `make lint` runs

- .github/workflows/images.yaml
- images/llvm/Dockerfile
- images/llvm/build-llvm.sh
- images/llvm/test/spec.yaml
This PR takes inspiration from #306 to update the build process of the binaries in the `llvm` image:
> main difference is that the resulting binaries are statically compiled. This allows them to run in a scratch image, drastically reducing the size of the docker image
The core differences are:
* `-DLLVM_BUILD_STATIC="ON"` -> ensures the produced binaries are statically linked
* `-DCMAKE_CXX_FLAGS="-s -flto"` -> ensures the produced binaries are stripped and use link time optimization
Since the binaries are now all static, they can be delivered in a `FROM scratch` image instead of the current `ubuntu` based image. This results in an overall smaller image.
Updating the build flags actually also leads to ~20% smaller binaries, contributing to a smaller final image:
* Current image:
| …
> llvm: Build optimized and static binaries

- images/checkpatch/checkpatch.sh
The blamed commit set the option to make the script fail if it tries to access any unbound variables, to catch possible errors. However, the script now fails when invoked directly, due to:
> ./checkpatch.sh: line 218: GITHUB_REF: unbound variable
While this is not a problem in practice, given that the Cilium's Makefile always sets the GITHUB_REF variable (possibly empty), let's guard the variable accesses, to be a bit more user-friendly.
Fixes: 5d11067d6e07 ("checkpatch: make script exit if command exits with error")
> checkpatch: prevent unbound variable error

- .github/renovate.json5
See #349
This PR configures renovate to recognize custom `# renovate:` comments in
Dockerfiles. One such comment is already present [here](https://github.com/cilium/image-tools/blob/49d7b282e76f941d6bf5abc4f125d14a1a7b2211/images/bpftool/Dockerfile#L12) (since https://github.com/cilium/image-tools/pull/366) and will allow to validate that this renovate config works as expected. If that is the case, we will be able to add more renovate comments to manage the versioning of other tools as listed in https://github.com/cilium/image-tools/issues/349.
This is largely inspired from the renovate config in cilium/cilium.
> Add renovate custom regex manager to tool updates
